### ISSUE TITLE
[Feature Request] Dynmon service enhancements

### ISSUE THREAD

**Issue by s41m0n** [polycube-network/polycube#291]
## Background
Recently, I have been using the new Dynmon service to test dynamic code injection and metrics extraction. Everything works as expected, but I would like to propose some enhancements that could increase the usability and customization of that service.

## Suggestions
The main innovations that came up to are the following:
- [x] Introduce support for the egress dataplane path (#311)
- [x] Introduce key exporting feature (for hash-based type maps) (#303)
- [x] Introduce fields inside an accepted metric to decide whether once the map associated to that metric is exported should be emptied or not (#311 )
- [x] Introduce duplication of the map requested by the user not only to speed up metric extraction, but also to avoid dataplane to be stuck waiting for the map's lock to be released by controlplane (#311 )
- [x] Enlarge Dynmon map extraction support, allowing reading:
 - Queue/Stack
 - Array types
 - Hash types
 - PerCPU types

The last one is the less essential, since it is not strictly related to the parameterization of the service, but to his performance.

**Comment by s41m0n** [comment]
#311 and #312 have introduced all the features, this issue can be closed
